all_arch:
	make -C fpu_test all_arch
	make -C fpu_test2 all_arch
	make -C dhrystone all_arch
	make -C coremark all_arch
	make -C machine all_arch
	make -C supervisor all_arch
	make -C freertosDemo all_arch
	make -C mmu_sv32 all_arch
	make -C mmu_sv39 all_arch
	make -C fpu_test3 all_arch
