define OPENSBI_NAX_PLATFORM_COPY
	cp -r $(BR2_TARGET_OPENSBI_PLAT_PATH) $(BUILD_DIR)/opensbi-$(OPENSBI_VERSION)/platform/$(BR2_TARGET_OPENSBI_PLAT)
endef

ifneq ($(BR2_TARGET_OPENSBI_PLAT_PATH),)
OPENSBI_PRE_BUILD_HOOKS += OPENSBI_NAX_PLATFORM_COPY
endif

